export const GET_NASA_IMAGE_SUCCESS = 'GET_NASA_IMAGE_SUCCESS';
export const GET_NASA_IMAGE_ERROR = 'GET_NASA_IMAGE_ERROR';

export const ADD_IMAGE_TO_LIKED = 'ADD_IMAGE_TO_LIKED';
export const REMOVE_IMAGE_FROM_LIKED = 'REMOVE_IMAGE_FROM_LIKED';
